name: Echo Statement

on:
  push:
    branches:
      - master
      - main

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo a statement
        run: echo "CI for foofoo"
